config/routes.rb
Motivation::Application.routes.draw do
  resources :motivators

  root :to => 'motivators#index'

end

app/models/motivator.rb
class Motivator < ActiveRecord::Base
  attr_accessible :body, :description, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/motivators_controller.rb
class MotivatorsController < ApplicationController
  # GET /motivators
  # GET /motivators.json
  def index
    @motivators = Motivator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @motivators }
    end
  end

  # GET /motivators/1
  # GET /motivators/1.json
  def show
    @motivator = Motivator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @motivator }
    end
  end

  # GET /motivators/new
  # GET /motivators/new.json
  def new
    @motivator = Motivator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @motivator }
    end
  end

  # GET /motivators/1/edit
  def edit
    @motivator = Motivator.find(params[:id])
  end

  # POST /motivators
  # POST /motivators.json
  def create
    @motivator = Motivator.new(params[:motivator])

    respond_to do |format|
      if @motivator.save
        format.html { redirect_to @motivator, notice: 'Motivator was successfully created.' }
        format.json { render json: @motivator, status: :created, location: @motivator }
      else
        format.html { render action: "new" }
        format.json { render json: @motivator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /motivators/1
  # PUT /motivators/1.json
  def update
    @motivator = Motivator.find(params[:id])

    respond_to do |format|
      if @motivator.update_attributes(params[:motivator])
        format.html { redirect_to @motivator, notice: 'Motivator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @motivator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motivators/1
  # DELETE /motivators/1.json
  def destroy
    @motivator = Motivator.find(params[:id])
    @motivator.destroy

    respond_to do |format|
      format.html { redirect_to motivators_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motivation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/motivators/_form.html.erb
<%= form_for(@motivator) do |f| %>
  <% if @motivator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@motivator.errors.count, "error") %> prohibited this motivator from being saved:</h2>

      <ul>
      <% @motivator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motivators/edit.html.erb
<h1>Editing motivator</h1>

<%= render 'form' %>

<%= link_to 'Show', @motivator %> |
<%= link_to 'Back', motivators_path %>

app/views/motivators/index.html.erb
<h1>Listing motivators</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @motivators.each do |motivator| %>
  <tr>
    <td><%= motivator.title %></td>
    <td><%= motivator.body %></td>
    <td><%= motivator.description %></td>
    <td><%= link_to 'Show', motivator %></td>
    <td><%= link_to 'Edit', edit_motivator_path(motivator) %></td>
    <td><%= link_to 'Destroy', motivator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Motivator', new_motivator_path %>

app/views/motivators/new.html.erb
<h1>New motivator</h1>

<%= render 'form' %>

<%= link_to 'Back', motivators_path %>

app/views/motivators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @motivator.title %>
</p>

<p>
  <b>Body:</b>
  <%= @motivator.body %>
</p>

<p>
  <b>Description:</b>
  <%= @motivator.description %>
</p>


<%= link_to 'Edit', edit_motivator_path(@motivator) %> |
<%= link_to 'Back', motivators_path %>